"use client"
import { Raleway } from 'next/font/google'
import './globals.css'
import HeaderNavBar from './components/HeaderNavBar'
import { useEffect, useState } from 'react'
import Provider from './Provider'
import { UserLocationContext } from '../context/UserLocationContext'

const raleway = Raleway({ subsets: ['latin'] })

/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/

export default function RootLayout({ children }) {


  const [userLocation, setUserLocation]=useState([]);
  useEffect(()=>{
    getUserLocation();
  },[])
  const getUserLocation=()=>{
    navigator.geolocation.getCurrentPosition(function(pos){
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })      
    })
  }

  return (
    <html lang="en">
      <body className={raleway.className}>
        <Provider>
          <UserLocationContext.Provider value={{userLocation, setUserLocation}}>
            <HeaderNavBar/>
            {children}
          </UserLocationContext.Provider>
        </Provider>
     

     

      </body>

    </html>
  )
}
